services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - site_media:/app/blitz_board/media
    depends_on:
      - db

  db:
    image: postgres:15-bookworm
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/

volumes:
  site_media: {}
  database: {}
