services:
  nginx:
    build: ./nginx/
    ports:
      - "8000:80"
    volumes:
      - site_media:/app/blitz_board/media
      - static:/app/blitz_board/static
    depends_on:
      - web

  web:
    build: .
    volumes:
      - site_media:/app/blitz_board/media
      - static:/app/blitz_board/static
    depends_on:
      - db

  db:
    image: postgres:15-bookworm
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/

volumes:
  site_media: {}
  static: {}
  database: {}
