[tool.poetry]
name = "social-snake"
version = "0.1.0"
description = "Puzzle Haven"
authors = ["Rehatbir Singh <rehatbir.singh@gmail.com>"]
readme = "README.md"
packages = [{include = "social_snake"}]

[tool.poetry.dependencies]
python = "^3.11"
quart = "^0.18.4"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.262"

[tool.poetry.scripts]
start = "social_snake:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
