[tool.poetry]
name = "social-snake"
version = "0.1.0"
description = "Puzzle Haven"
authors = ["Rehatbir Singh <rehatbir.singh@gmail.com>"]
readme = "README.md"
packages = [{include = "social_snake"}]

[tool.poetry.dependencies]
python = "^3.11"
quart = "^0.18.4"
quart-sqlalchemy = "^2.0.0"
python-dotenv = "^1.0.0"
psycopg2 = "^2.9.6"
quart-wtf = "^0.0.1"
email-validator = "^2.0.0.post2"
aiosmtplib = "^2.0.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.262"
alembic = "^1.10.4"

[tool.poetry.scripts]
start = "social_snake:run"

[tool.ruff]
ignore = ["E402"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
