"""unverified user model

Revision ID: 13942301b9bd
Revises: ec6f945dca77
Create Date: 2023-04-29 11:09:05.237191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13942301b9bd"
down_revision = "ec6f945dca77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unverified_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("url_code", sa.Uuid(), nullable=False),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("url_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unverified_user")
    # ### end Alembic commands ###
