"""updated magic links model

Revision ID: 435f4a2340a5
Revises: b5ad8a3d2cd2
Create Date: 2023-05-03 23:20:42.147915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "435f4a2340a5"
down_revision = "b5ad8a3d2cd2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "magic_link", sa.Column("user", sa.Integer(), nullable=False)
    )
    op.add_column(
        "magic_link", sa.Column("url_code", sa.Uuid(), nullable=False)
    )
    op.add_column(
        "magic_link", sa.Column("valid_until", sa.DateTime(), nullable=False)
    )
    op.create_unique_constraint(None, "magic_link", ["url_code"])
    op.create_foreign_key(None, "magic_link", "users", ["user"], ["id"])
    op.drop_column("magic_link", "user_id")
    op.drop_column("magic_link", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "magic_link",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "magic_link",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "magic_link", type_="foreignkey")
    op.drop_constraint(None, "magic_link", type_="unique")
    op.drop_column("magic_link", "valid_until")
    op.drop_column("magic_link", "url_code")
    op.drop_column("magic_link", "user")
    # ### end Alembic commands ###
