"""channels table

Revision ID: 48625fa0f108
Revises: 9f3897231ff9
Create Date: 2023-09-14 07:36:34.840405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48625fa0f108"
down_revision = "9f3897231ff9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("members", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "messages", sa.Column("author_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "messages", sa.Column("channel_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "messages_recipient_fkey", "messages", type_="foreignkey"
    )
    op.drop_constraint("messages_author_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "users", ["author_id"], ["id"])
    op.create_foreign_key(
        None, "messages", "message_channels", ["channel_id"], ["id"]
    )
    op.drop_column("messages", "author")
    op.drop_column("messages", "recipient")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "recipient", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "messages",
        sa.Column("author", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "messages", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "messages_author_fkey", "messages", "users", ["author"], ["id"]
    )
    op.create_foreign_key(
        "messages_recipient_fkey", "messages", "users", ["recipient"], ["id"]
    )
    op.drop_column("messages", "channel_id")
    op.drop_column("messages", "author_id")
    op.drop_table("message_channels")
    # ### end Alembic commands ###
