"""friend requests table

Revision ID: 59da9090a5b7
Revises: a6b362244456
Create Date: 2023-09-17 22:16:45.903848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59da9090a5b7"
down_revision = "a6b362244456"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend_requests",
        sa.Column("from_id", sa.Integer(), nullable=False),
        sa.Column("to_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("from_id", "to_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friend_requests")
    # ### end Alembic commands ###
