"""added published field

Revision ID: 809457375ab2
Revises: 9bfb1add6354
Create Date: 2023-05-07 18:29:44.597034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "809457375ab2"
down_revision = "9bfb1add6354"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maze", sa.Column("published", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maze", "published")
    # ### end Alembic commands ###
