"""created maze model

Revision ID: 9bfb1add6354
Revises: ba84877586ec
Create Date: 2023-05-06 11:03:16.995259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9bfb1add6354"
down_revision = "ba84877586ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maze",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=True),
        sa.Column("maze_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maze")
    # ### end Alembic commands ###
