"""added friends table

Revision ID: eb3a50d7f1e6
Revises: 59da9090a5b7
Create Date: 2023-09-28 09:17:55.342788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb3a50d7f1e6"
down_revision = "59da9090a5b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friends",
        sa.Column("left_id", sa.Integer(), nullable=False),
        sa.Column("right_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friends")
    # ### end Alembic commands ###
